env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures": 
    - jsx: true
rules:
  consistent-return: 2
  indent: [1, 4]
  no-else-return: 1
  semi: [1, "always"]
  space-unary-ops: 2
  no-extra-semi: 1
  no-mixed-spaces-and-tabs: 1