env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures": 
    - jsx: true
rules:
  # import/prefer-default-export: 1
  no-trailing-spaces: 1
  comma-dangle: ["error", "objects": "always-multiline"]
  quote-props: ["error", "as-needed"]
  object-curly-newline: 1
  no-multiple-empty-lines: 1
  eol-last: 1
  arrow-body-style: 1
  # quotes: 1
  consistent-return: 2
  indent: ["error", 2, { "SwitchCase": 1 }]
  no-else-return: 1
  semi: [1, "always"]
  space-unary-ops: 2
  no-extra-semi: 1
  no-mixed-spaces-and-tabs: 1